name: Update Dist

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.js'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install @vercel/ncc
        run: npm install -g @vercel/ncc

      - name: Install dependencies
        run: npm ci

      - name: Build with @vercel/ncc
        run: ncc build src/index.js -o dist --license licenses.txt

      - name: Check for changes in dist
        id: check
        run: |
          git diff --quiet dist/ || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/index.js
          git add dist/licenses.txt
          git commit -m "Update dist" && git push
